In [59]:
import pandas as pd
from mlxtend.preprocessing import minmax_scaling

In [60]:
df= pd.read_excel("/content/drive/MyDrive/lab2file.xlsx")
df

    Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0        1          1             4512                 1530
1        1          1             3738                 1297
2        1          1             4261                 1335
3        1          1             3777                 1282
4        1          1             4177                 1590
5        1          1             3585                 1300
6        1          1             3785                 1400
7        1          1             3559                 1255
8        1          2             3613                 1355
9        2          2             3982                 1375
10       2          2             3443                 1340
11       2          2             3993                 1380
12       2          2             3640                 1355
13       2          2             4208                 1522
14       2          2             3832                 1208

In [61]:
columns = ['Gender','Age Range', 'Head Size(cm^3)', 'Brain Weight(grams)']
df_scaled = minmax_scaling(df, columns=columns)

In [62]:
print("\nScaled Data (Min-Max Scaling):")
print(df_scaled)

Scaled Data (Min-Max Scaling):
    Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0      0.0        0.0         1.000000             0.842932
1      0.0        0.0         0.275959             0.232984
2      0.0        0.0         0.765201             0.332461
3      0.0        0.0         0.312442             0.193717
4      0.0        0.0         0.686623             1.000000
5      0.0        0.0         0.132834             0.240838
6      0.0        0.0         0.319925             0.502618
7      0.0        0.0         0.108513             0.123037
8      0.0        1.0         0.159027             0.384817
9      1.0        1.0         0.504210             0.437173
10     1.0        1.0         0.000000             0.345550
11     1.0        1.0         0.514500             0.450262
12     1.0        1.0         0.184284             0.384817
13     1.0        1.0         0.715622             0.821990
14     1.0        1.0         0.363891             0.000000

In [63]:
from sklearn.model_selection import train_test_split
hx=pd.read_csv('/content/drive/MyDrive/housing.csv')
hx

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [64]:
discription=hx.describe()
print(discription)

          longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000
mean    -119.569704     35.631861           28.639486   2635.763081
std        2.003532      2.135952           12.585558   2181.615252
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.800000     33.930000           18.000000   1447.750000
50%     -118.490000     34.260000           29.000000   2127.000000
75%     -118.010000     37.710000           37.000000   3148.000000
max     -114.310000     41.950000           52.000000  39320.000000

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000
mean       537.870553   1425.476744    499.539680       3.870671
std        421.385070   1132.462122    382.329753       1.899822
min          1.000000      3.000000      1.000000       0.499900
25%        296.000000    787.000000    280.000000       2.563400
50%        435.000000   1166.000000    409.000000       3.534800
75%        647.000000   1725.000000    605.000000       4.743250
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        20640.000000
mean        206855.816909
std         115395.615874
min          14999.000000
25%         119600.000000
50%         179700.000000
75%         264725.000000
max         500001.000000

In [65]:
data_type=hx.dtypes
print('data_type=\n',data_type)

data_type=
 longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

In [66]:
data_shape=hx.shape
print('data_shape=',data_shape)

data_shape= (20640, 10)

In [67]:
data_null=hx.isnull().sum()
print('if data is null=\n',data_null)

if data is null=
 longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [68]:
replace_null=hx.fillna(0)
print(replace_null)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0
1        -122.22     37.86                21.0       7099.0          1106.0
2        -122.24     37.85                52.0       1467.0           190.0
3        -122.25     37.85                52.0       1274.0           235.0
4        -122.25     37.85                52.0       1627.0           280.0
...          ...       ...                 ...          ...             ...
20635    -121.09     39.48                25.0       1665.0           374.0
20636    -121.21     39.49                18.0        697.0           150.0
20637    -121.22     39.43                17.0       2254.0           485.0
20638    -121.32     39.43                18.0       1860.0           409.0
20639    -121.24     39.37                16.0       2785.0           616.0

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0
1          2401.0      1138.0         8.3014            358500.0
2           496.0       177.0         7.2574            352100.0
3           558.0       219.0         5.6431            341300.0
4           565.0       259.0         3.8462            342200.0
...           ...         ...            ...                 ...
20635       845.0       330.0         1.5603             78100.0
20636       356.0       114.0         2.5568             77100.0
20637      1007.0       433.0         1.7000             92300.0
20638       741.0       349.0         1.8672             84700.0
20639      1387.0       530.0         2.3886             89400.0

      ocean_proximity
0            NEAR BAY
1            NEAR BAY
2            NEAR BAY
3            NEAR BAY
4            NEAR BAY
...               ...
20635          INLAND
20636          INLAND
20637          INLAND
20638          INLAND
20639          INLAND

[20640 rows x 10 columns]

In [69]:
d=hx.drop('ocean_proximity', axis=1, inplace=True)
columns2 = ['longitude','latitude','housing_median_age', 'total_rooms','total_bedrooms', 'population','households','median_income', 'median_house_value']
data_scaled = minmax_scaling(hx, columns=columns2)
data_scaled

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,0.211155,0.567481,0.784314,0.022331,0.019863,0.008941,0.020556,0.539668,0.902266
1,0.212151,0.565356,0.392157,0.180503,0.171477,0.067210,0.186976,0.538027,0.708247
2,0.210159,0.564293,1.000000,0.037260,0.029330,0.013818,0.028943,0.466028,0.695051
3,0.209163,0.564293,1.000000,0.032352,0.036313,0.015555,0.035849,0.354699,0.672783
4,0.209163,0.564293,1.000000,0.041330,0.043296,0.015752,0.042427,0.230776,0.674638
...,...,...,...,...,...,...,...,...,...
20635,0.324701,0.737513,0.470588,0.042296,0.057883,0.023599,0.054103,0.073130,0.130105
20636,0.312749,0.738576,0.333333,0.017676,0.023122,0.009894,0.018582,0.141853,0.128043
20637,0.311753,0.732200,0.313725,0.057277,0.075109,0.028140,0.071041,0.082764,0.159383
20638,0.301793,0.732200,0.333333,0.047256,0.063315,0.020684,0.057227,0.094295,0.143713
20639,0.309761,0.725824,0.294118,0.070782,0.095438,0.038790,0.086992,0.130253,0.153403

In [74]:
target_variable = 'median_house_value'

X = hx.drop(target_variable, axis=1)
y = hx[target_variable]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Train set shapes - X_train:", X_train.shape, "y_train:", y_train.shape)
print("Test set shapes - X_test:", X_test.shape, "y_test:",y_test.shape)

Train set shapes - X_train: (16512, 8) y_train: (16512,)
Test set shapes - X_test: (4128, 8) y_test: (4128,)